image: atlassian/default-image:5
clone:
  depth: full

definitions:
  services:
    docker:
      memory: 3072

  steps:
    - step: &docker-build
        name: 🚧 Docker Build (validate)
        services:
          - docker
        script:
          - export DOCKER_BUILDKIT=0
          - docker build --build-arg NODE_TAG=${NODE_TAG} -t "${BITBUCKET_REPO_SLUG}:pr-${BITBUCKET_PR_ID}" .

    - step: &push-docker-build
        name: 🛫 Build and Push Docker Image
        services:
          - docker
        script:
          - mkdir -vp ~/.docker/cli-plugins/
          - ARCH=amd64
          - BUILDX_URL=$(curl -s https://raw.githubusercontent.com/docker/actions-toolkit/main/.github/buildx-lab-releases.json | jq -r ".latest.assets[] | select(endswith(\"linux-$ARCH\"))")
          - curl --silent -L --output ~/.docker/cli-plugins/docker-buildx "$BUILDX_URL"
          - chmod a+x ~/.docker/cli-plugins/docker-buildx

          - echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_ACCOUNT" --password-stdin
          - docker buildx create --use --driver cloud "${DOCKER_ACCOUNT}/${CLOUD_BUILDER_NAME}"

          - IMAGE_NAME=${DOCKER_ACCOUNT}/$BITBUCKET_REPO_SLUG
          - |
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --push \
              --build-arg NODE_TAG=${NODE_TAG} \
              --tag "${IMAGE_NAME}:${NODE_TAG}" \
              .

pipelines:
  pull-requests:
    '**':
      - step:
          <<: *docker-build
          name: "🚧 Docker Build"
  branches:
    main:
      - step:
          <<: *push-docker-build
          name: "🛫 Build and Push Docker Image"
          deployment: main